# apiVersion: secrets.crossplane.io/v1alpha1
# kind: StoreConfig
# metadata:
#   name: vault
#   labels:
#     {{- include "aws-provisioner.labels" . | nindent 4 }}   
# spec:
#   type: Vault
#   defaultScope: {{ .Release.Namespace }}
#   vault:
#     server: "https://vault.apps.cluster-q4dlx.q4dlx.sandbox744.opentlc.com"
#     mountPath: crossplane/
#     version: v2
#     auth:
#       method: Token
#       token:
#         source: Filesystem
#         fs:
#           path: /vault/secrets/token"